on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.python]
command = "black"
includes = ["*.py"]

[formatter.robotidy]
command = "robotidy"
includes = ["*.robot"]
