[project]
name = "tasks"
version = "0.0.1"
dependencies = [
    "purjo",
    "robotframework-robocop>=6.6.1",
]
requires-python = ">=3.11"

[tool.uv.sources]
purjo = { git = "https://github.com/datakurre/purjo.git" }
